version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: LOGIN
  
  main:
    build: main/.
    links: 
      - db
    restart: always
    ports: 
      - 3000:3000
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db:3306", "-t", "50", "--", "npm", "run", "start:prod"]

  password:
    build: password/.
    restart: always
    ports: 
      - 3001:3001


